SLMap = {0: 0.3, 1: 1, 2: 0}
adjustmentPercent = 0.3
initialPremium = 50
mtmStopLoss = 20
path = "C:\\Users\\Safwan PC\\banknifty_new\\"
index = "NIFTY"
indexToken = "26000"
strikeDifference = 50
noOfAdjustment = 1
oneSideFullHitFlag = True