isMonthly = False

parameters = [
    {
        "SLMap": {0: 0.2, 1: 1, 2: 1},
        "adjustmentPercent": 0.2,
        "initialPremiumMultiplier": 0.005,
        "mtmStopLoss": 0.004,
        "index": "BANKNIFTY",
        "lotSize": 1,
        "expDate": "24731",
        "indexExchange": "NSE",
        "fnoExchange": "NFO",
        "strikeDifference": 100,
        "noOfAdjustment": 1,
        "oneSideFullHitFlag": True,
        "daysBeforeExpiry": 2,
        "adjustmentShift": True,
        "shiftAmount": 0.0001,
        "startTime": "09:45:00",
        "hedgeDist": 30,
        "overNightHedgeDist": 5,
        "isPositional": True,
        "strategyTag": "OPTIONSPLAYPOSITIONAL"
    },
{
        "SLMap": {0: 0.2, 1: 1, 2: 1},
        "adjustmentPercent": 0.2,
        "initialPremiumMultiplier": 0.005,
        "mtmStopLoss": 0.004,
        "index": "BANKNIFTY",
        "lotSize": 1,
        "expDate": "24731",
        "indexExchange": "NSE",
        "fnoExchange": "NFO",
        "strikeDifference": 100,
        "noOfAdjustment": 1,
        "oneSideFullHitFlag": True,
        "daysBeforeExpiry": 1,
        "adjustmentShift": True,
        "shiftAmount": 0.0001,
        "startTime": "09:45:00",
        "hedgeDist": 30,
        "overNightHedgeDist": 5,
        "isPositional": True,
        "strategyTag": "OPTIONSPLAYPOSITIONAL"
    },
{
        "SLMap": {0: 0.2, 1: 1, 2: 1},
        "adjustmentPercent": 0.2,
        "initialPremiumMultiplier": 0.01,
        "mtmStopLoss": 0.005,
        "index": "BANKNIFTY",
        "lotSize": 1,
        "expDate": "24731",
        "indexExchange": "NSE",
        "fnoExchange": "NFO",
        "strikeDifference": 100,
        "noOfAdjustment": 1,
        "oneSideFullHitFlag": True,
        "daysBeforeExpiry": 4,
        "adjustmentShift": True,
        "shiftAmount": 0.0003,
        "startTime": "13:59:00",
        "hedgeDist": 30,
        "overNightHedgeDist": 5,
        "isPositional": True,
        "strategyTag": "OPTIONSPLAYPOSITIONAL"
    }
]

# parameters = [
#     {
#         "SLMap": {0: 0.4, 1: 1, 2: 1},
#         "adjustmentPercent": 0.2,
#         "initialPremiumMultiplier": 0.003,
#         "mtmStopLoss": 0.02,
#         "index": "BANKNIFTY",
#         "lotSize": 2,
#         "expDate": "24724",
#         "indexExchange": "NSE",
#         "fnoExchange": "NFO",
#         "strikeDifference": 100,
#         "noOfAdjustment": 1,
#         "oneSideFullHitFlag": True,
#         "daysBeforeExpiry": 0,
#         "adjustmentShift": False,
#         "shiftAmount": 0.0003,
#         "startTime": "13:00:00",
#         "hedgeDist": 10,
#         "overNightHedgeDist": 4,
#         "isPositional": False,
#         "strategyTag": "OPTIONSPLAY1PM"
#     },
# {
#         "SLMap": {0: 0.5, 1: 1, 2: 1},
#         "adjustmentPercent": 0.2,
#         "initialPremiumMultiplier": 0.003,
#         "mtmStopLoss": 0.02,
#         "index": "BANKNIFTY",
#         "lotSize": 2,
#         "expDate": "24724",
#         "indexExchange": "NSE",
#         "fnoExchange": "NFO",
#         "strikeDifference": 100,
#         "noOfAdjustment": 1,
#         "oneSideFullHitFlag": True,
#         "daysBeforeExpiry": 0,
#         "adjustmentShift": False,
#         "shiftAmount": 0.0003,
#         "startTime": "13:30:00",
#         "hedgeDist": 8,
#         "overNightHedgeDist": 4,
#         "isPositional": False,
#         "strategyTag": "OPTIONSPLAY1PM"
#     },
# {
#         "SLMap": {0: 0.6, 1: 1, 2: 1},
#         "adjustmentPercent": 0.2,
#         "initialPremiumMultiplier": 0.003,
#         "mtmStopLoss": 0.02,
#         "index": "BANKNIFTY",
#         "lotSize": 2,
#         "expDate": "24724",
#         "indexExchange": "NSE",
#         "fnoExchange": "NFO",
#         "strikeDifference": 100,
#         "noOfAdjustment": 1,
#         "oneSideFullHitFlag": True,
#         "daysBeforeExpiry": 0,
#         "adjustmentShift": False,
#         "shiftAmount": 0.0003,
#         "startTime": "13:59:00",
#         "hedgeDist": 6,
#         "overNightHedgeDist": 4,
#         "isPositional": False,
#         "strategyTag": "OPTIONSPLAY1PM"
#     },
# {
#         "SLMap": {0: 0.6, 1: 1, 2: 1},
#         "adjustmentPercent": 0.2,
#         "initialPremiumMultiplier": 0.003,
#         "mtmStopLoss": 0.02,
#         "index": "BANKNIFTY",
#         "lotSize": 2,
#         "expDate": "24724",
#         "indexExchange": "NSE",
#         "fnoExchange": "NFO",
#         "strikeDifference": 100,
#         "noOfAdjustment": 1,
#         "oneSideFullHitFlag": True,
#         "daysBeforeExpiry": 0,
#         "adjustmentShift": False,
#         "shiftAmount": 0.0003,
#         "startTime": "14:29:00",
#         "hedgeDist": 5,
#         "overNightHedgeDist": 4,
#         "isPositional": False,
#         "strategyTag": "OPTIONSPLAY1PM"
#     },
# {
#         "SLMap": {0: 100, 1: 1, 2: 1},
#         "adjustmentPercent": 0.2,
#         "initialPremiumMultiplier": 0.003,
#         "mtmStopLoss": 0.02,
#         "index": "BANKNIFTY",
#         "lotSize": 2,
#         "expDate": "24724",
#         "indexExchange": "NSE",
#         "fnoExchange": "NFO",
#         "strikeDifference": 100,
#         "noOfAdjustment": 1,
#         "oneSideFullHitFlag": True,
#         "daysBeforeExpiry": 0,
#         "adjustmentShift": False,
#         "shiftAmount": 0.0003,
#         "startTime": "14:59:00",
#         "hedgeDist": 5,
#         "overNightHedgeDist": 4,
#         "isPositional": False,
#         "strategyTag": "OPTIONSPLAY1PM"
#     },
# #     {
# #         "SLMap": {0: 0.2, 1: 1, 2: 1},
# #         "adjustmentPercent": 0.2,
# #         "initialPremiumMultiplier": 0.01,
# #         "mtmStopLoss": 0.005,
# #         "index": "BANKNIFTY",
# #         "lotSize": 1,
# #         "expDate": "24725",
# #         "indexExchange": "NSE",
# #         "fnoExchange": "NFO",
# #         "strikeDifference": 50,
# #         "noOfAdjustment": 1,
# #         "oneSideFullHitFlag": True,
# #         "daysBeforeExpiry": 6,
# #         "adjustmentShift": True,
# #         "shiftAmount": 0.0003,
# #         "startTime": "14:44:00",
# #         "hedgeDist": 20,
# #         "overNightHedgeDist": 5,
# #         "isPositional": True,
# #         "strategyTag": "OPTIONSPLAYPOSITIONAL"
# #     },
# #     {
# #         "SLMap": {0: 0.2, 1: 1, 2: 1},
# #         "adjustmentPercent": 0.2,
# #         "initialPremiumMultiplier": 0.01,
# #         "mtmStopLoss": 0.005,
# #         "index": "BANKNIFTY",
# #         "lotSize": 1,
# #         "expDate": "24725",
# #         "indexExchange": "NSE",
# #         "fnoExchange": "NFO",
# #         "strikeDifference": 50,
# #         "noOfAdjustment": 1,
# #         "oneSideFullHitFlag": True,
# #         "daysBeforeExpiry": 5,
# #         "adjustmentShift": True,
# #         "shiftAmount": 0.0003,
# #         "startTime": "09:44:00",
# #         "hedgeDist": 20,
# #         "overNightHedgeDist": 5,
# #         "isPositional": True,
# #         "strategyTag": "OPTIONSPLAYPOSITIONAL"
# #     },
# #     {
# #         "SLMap": {0: 0.2, 1: 1, 2: 1},
# #         "adjustmentPercent": 0.2,
# #         "initialPremiumMultiplier": 0.01,
# #         "mtmStopLoss": 0.005,
# #         "index": "BANKNIFTY",
# #         "lotSize": 1,
# #         "expDate": "24725",
# #         "indexExchange": "NSE",
# #         "fnoExchange": "NFO",
# #         "strikeDifference": 50,
# #         "noOfAdjustment": 1,
# #         "oneSideFullHitFlag": True,
# #         "daysBeforeExpiry": 5,
# #         "adjustmentShift": True,
# #         "shiftAmount": 0.0003,
# #         "startTime": "14:44:00",
# #         "hedgeDist": 20,
# #         "overNightHedgeDist": 5,
# #         "isPositional": True,
# #         "strategyTag": "OPTIONSPLAYPOSITIONAL"
# #     },
# #     {
# #         "SLMap": {0: 0.2, 1: 1, 2: 1},
# #         "adjustmentPercent": 0.2,
# #         "initialPremiumMultiplier": 0.01,
# #         "mtmStopLoss": 0.005,
# #         "index": "BANKNIFTY",
# #         "lotSize": 1,
# #         "expDate": "24725",
# #         "indexExchange": "NSE",
# #         "fnoExchange": "NFO",
# #         "strikeDifference": 50,
# #         "noOfAdjustment": 1,
# #         "oneSideFullHitFlag": True,
# #         "daysBeforeExpiry": 2,
# #         "adjustmentShift": True,
# #         "shiftAmount": 0.0002,
# #         "startTime": "09:44:00",
# #         "hedgeDist": 20,
# #         "overNightHedgeDist": 5,
# #         "isPositional": True,
# #         "strategyTag": "OPTIONSPLAYPOSITIONAL"
# #     },
# #     {
# #         "SLMap": {0: 0.2, 1: 1, 2: 1},
# #         "adjustmentPercent": 0.2,
# #         "initialPremiumMultiplier": 0.005,
# #         "mtmStopLoss": 0.005,
# #         "index": "BANKNIFTY",
# #         "lotSize": 1,
# #         "expDate": "24725",
# #         "indexExchange": "NSE",
# #         "fnoExchange": "NFO",
# #         "strikeDifference": 50,
# #         "noOfAdjustment": 1,
# #         "oneSideFullHitFlag": True,
# #         "daysBeforeExpiry": 2,
# #         "adjustmentShift": True,
# #         "shiftAmount": 0.0002,
# #         "startTime": "14:44:00",
# #         "hedgeDist": 20,
# #         "overNightHedgeDist": 5,
# #         "isPositional": True,
# #         "strategyTag": "OPTIONSPLAYPOSITIONAL"
# #     },
# # {
# #         "SLMap": {0: 0.2, 1: 1, 2: 1},
# #         "adjustmentPercent": 0.2,
# #         "initialPremiumMultiplier": 0.005,
# #         "mtmStopLoss": 0.005,
# #         "index": "BANKNIFTY",
# #         "lotSize": 1,
# #         "expDate": "24725",
# #         "indexExchange": "NSE",
# #         "fnoExchange": "NFO",
# #         "strikeDifference": 50,
# #         "noOfAdjustment": 1,
# #         "oneSideFullHitFlag": True,
# #         "daysBeforeExpiry": 2,
# #         "adjustmentShift": True,
# #         "shiftAmount": 0.0002,
# #         "startTime": "14:44:00",
# #         "hedgeDist": 20,
# #         "overNightHedgeDist": 5,
# #         "isPositional": True,
# #         "strategyTag": "OPTIONSPLAYPOSITIONAL"
# #     },
# ]
